### ISSUE TITLE
Del does not work as expected on IE11

### ISSUE THREAD

**Issue by ftaffelt** [jcubic/jquery.terminal#302]
### Expected behavior
delete char to right of cursor
### Actual behavior
nothing
### Steps to reproduce
- on IE11 go to http://codepen.io/jcubic/pen/MbVMwO 
- enter 1
- use left arrow to move the cursor to 1 
- press DEL

**Comment by jcubic** [comment]
In IE11 the key property for delete key is `Del` not `Delete` like in other browsers, fixed in master branch.

**Comment by ftaffelt** [comment]
thank you for the fast fix.

**Comment by ftaffelt** [comment]
it seems that this issue is back again in latest version 1.1.0

**Comment by jcubic** [comment]
it was a typo fixed now.

**Comment by jcubic** [comment]
It's in master branch that already have version 1.1.1 but it's not yet released.
